# location of the reference genome on longleaf
ref_name: 'dm6'
reference: '/proj/seq/data/dm6/UCSC/Sequence/WholeGenomeFasta/genome.fa'

# Illumina sequences are assumed to be paired
sequencer: "novaseq" # hiseq, novaseq or nanopore
aligner: "bwa" # bwa or bowtie2
caller: "bcftools" # bcftools or freebayes
bcftools_opts:
  call_as_groups: False
# mask repeats in the reference genome?
mask_repeats: True

trimming: True
trimming_opts:
# adapter sequences
# nanopore data is returned demultiplexed and with adapters trimmed
  adapters:
    fwd: 'AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT'
    rev: 'GATCGGAAGAGCACACGTCTGAACTCCAGTCACGGATGACTATCTCGTATGCCGTCTTCTGCTTG'

chroms:
  - 'chrX'
  - 'chr2L'
  - 'chr2R'
  - 'chr3L'
  - 'chr3R'
  - 'chr4'

freebayes_opts:
  nchunks: 2

filtering:
  variant_quality: True
  variant_quality_level: "strict" # options are strict, moderate, lenient or off
# you can manually edit the quality cutoffs here
  variant_quality_cutoff_values:
    bcftools:
      strict: 200
      moderate: 100
      lenient: 50
    freebayes:
      strict: 1000 * progeny[n]
      moderate: 500 * progeny[n]
      lenient: 100 * progeny[n]

ndj_analysis: False
ndj_analysis_opts:
  parents:
    ref_parent: 'w1118'
    alt_parent: 'oregonr'

# options are tsvs (for loading calls into R), consensus (consensus sequences from calls), calls, or alignments
output: 'consensus'
