# options are tsvs (for loading calls into R), consensus (consensus sequences from calls), calls, or alignments
output: 'tsvs'

# location of the reference genome on longleaf
ref_name: 'dm6'
reference: '/proj/seq/data/dm6_UCSC/Sequence/WholeGenomeFasta/genome.fa'
mask_repeats: True

# file locations to use in the sample sheet.
# If location is set to proj for paired sample A, snakemake will look for the files:
# /proj/sekellab/projects/pipeline_test/A_1.fq.gz
# /proj/sekellab/projects/pipeline_test/A_2.fq.gz
data_locations:
  proj: "/work/users/c/a/cannecar/pipeline_test/"

illumina:
  aligner: "bwa" # bwa or bowtie2

caller: "bcftools" # bcftools or freebayes

# how to filter variants
filtering:
    - "QUAL>10" # basic quality filtering
    - "QUAL/AO > 10" # scale quality by depth
    - "DP > 20 & DP < 200" # depth cutoffs
    - "SAF > 0 & SAR > 0" # there must be forward and reverse reads supporting the variant

bcftools_opts:
  call_as_groups: False

