executor: slurm
latency-wait: 60
restart-times: 0
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
keep-going: True
rerun-incomplete: True
printshellcmds: True
use-conda: True
show-failed-logs: True
cache: True
use-envmodules: True
jobs: 500

default-resources:
  slurm_partition: general
  runtime: 60
  slurm_extra: "'--mail-type=FAIL --mail-user=cannecar@ad.unc.edu'"

set-resources:
  minimap2_idx:
    mem_mb: 40000
  align_bowtie2:
    runtime: 1440
  align_minimap2:
    runtime: 1440
    mem_mb: 40000
  sort_bams:
    mem_mb: 14000
  index_bams:
    runtime: 120
  bcftools_mpileup:
    mem_mb: 40000
    runtime: 1440
  bcftools_call:
    mem_mb: 40000
    runtime: 1440
  sort_bams:
    mem_mb: 20000
  mark_duplicates:
    mem_mb: 20000
  convert_tsv_to_parquet:
    mem_mb: 50000
  rearrange_reference_parquet:
    mem_mb: 50000
    runtime: 1440
  rearrange_sample_parquet:
    mem_mb: 50000
    runtime: 1440
  run_rtiger:
    mem_mb: 50000
  process_tiger_output:
    mem_mb: 150000
    runtime: 2880