cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/{rule}/{rule}-{wildcards}.out
    --time={resources.time}
    --mail-type="FAIL"
    --mail-user="cannecar@ad.unc.edu"
default-resources:
  - partition=general
  # - mem_mb=1000
  - time="1:00:00"
restart-times: 0
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 120
jobs: 500
keep-going: True
rerun-incomplete: True
printshellcmds: True
use-conda: True
