$schema: "http://json-schema.org/draft-07/schema#"
title: DNA sequencing pipeline configuration
description: Config file for sequencing pipeline
type: object
properties:
  ref_name:
    description: Name of the reference (can be anything)
    type: string
  reference:
    description: Path to the reference FASTA file
    type: string
  ref_parent:
    description: Name of the parent to be used as a reference (must match name in sample sheet)
    type: string
  alt_parent:
    description: Name of the other parent (must match name in sample sheet)
    type: string
  mask_repeats:
    description: Whether to mask repetitive sequences in the reference genome
    type: boolean
  data_locations:
    description: Shorthand identifiers for data file locations and the locations that they correspond to
    type: object
    properties:
      "*":
        type: string
    minItems: 1
required:
  - ref_name
  - reference
  - ref_parent
  - alt_parent
